Add convert function for string and bool
WolframResearch/wolfram-expr-rs pull request #7
Opened 2022-03-29 08:25 UTC by oovm

I think `try_*` does not follow the rust naming convention, should use `as_*`

2022-03-30 16:28 UTC, ConnorGray commented
@oovm Thank you for making these contributions!

I originally chose to use the `try_*` because I think these methods are more like `TryFrom/TryInto` conversions than `as_*` functions (which I think don't typically fail?). Though `as_*` does more clearly suggest that a conversion is happening. Perhaps `try_as_*`?

2022-03-30 21:00 UTC, ConnorGray requested changes
Thank you for submitting this pull request! :) 

New convenience functions like this will be a big help to reducing some of the verbosity that is currently required when working with expressions.

I've left a few comments about a couple of conversions that I think we might want to approach in a different way, perhaps in a future PR.

2022-04-01 09:42 UTC, oovm commented on src/lib.rs
> +impl From<()> for Expr {
You are right, I will remove `()` and `Option` both

2022-04-01 09:56 UTC, oovm commented
rebase complete

2022-04-22 14:51 UTC, ConnorGray requested changes
I apologize, I wrote out this second round of review comments several weeks ago, but apparently forgot to finish submitting them to the PR.

2022-04-23 03:21 UTC, oovm commented on src/lib.rs
> +    }
It is actually possible to design an auxiliary structure pub struct `Association {wrap: IndexMap}`

2022-04-23 03:24 UTC, oovm commented on src/lib.rs
> +    }
A lot of design is needed here, I'll implement this in the next pr if appropriate.

2022-05-17 04:43 UTC, merged

2022-05-17 04:46 UTC, ConnorGray commented
@oovm Thank you again for the PR!